# Generated by Django 3.0.6 on 2020-07-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
