# Generated by Django 3.0.6 on 2020-07-11 19:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0005_auto_20200711_0645'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='ProductCart',
        ),
    ]
